// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "uart_rs485.h"
static const char *TAG = "uart_rs485";
void shenwenkongzhi(lv_event_t *e)
{

	// // 要发送的16进制指令

	// uint8_t hex_cmd[] = {0xFE, 0x05, 0x00, 0x00, 0xFF, 0x00, 0x98, 0x35};

	// // 发送16进制指令
	// uart_write_bytes(UART_NUM_0, (const char *)hex_cmd, sizeof(hex_cmd));
}

void jianwenkongzhi(lv_event_t *e)
{

	// uint8_t hex_cmd[] = {0xFE, 0x05, 0x00, 0x01, 0xFF, 0x00, 0xC9, 0xF5};

	// // 发送16进制指令
	// uart_write_bytes(UART_NUM_0, (const char *)hex_cmd, sizeof(hex_cmd));
}
