// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: first_SquareLine_Project

#include "ui.h"
#include "pwm.h"//1，引入PWM头文件
void Eventpwmlight(lv_event_t * e)
{
	static char buf[8];

	lv_obj_t *slider = (lv_obj_t *)e->target;
	int brightness = lv_slider_get_value(slider);//获取滑动条值
	ESP_ERROR_CHECK(pwm_set_duty(brightness));//设置PWM值
	sprintf(buf, "%d%%", brightness);
	lv_label_set_text(ui_Label1, buf);//值显示
}
