// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void shenwenkongzhi(lv_event_t * e)
{
	// Your code here
}

void jianwenkongzhi(lv_event_t * e)
{
	// Your code here
}
